export const FETCH_STARSHIPS_REQUEST = 'FETCH_STARSHIPS_REQUEST';
export const FETCH_STARSHIPS_SUCCESS = 'FETCH_STARSHIPS_SUCCESS';
export const FETCH_STARSHIPS_FAILURE = 'FETCH_STARSHIPS_FAILURE';
export const SORT_STARSHIPS = 'SORT_STARSHIPS';
export const SORT_PASSENGERS = 'SORT_PASSENGERS';
// export const FETCH_STARSHIPS_MODEL = 'FETCH_STARSHIPS_MODEL';